emcasa/native

- .babelrc
- .env.example
- lib/api/index.js
- package.json
- yarn.lock
Inlines environment vars on build
> Fix build time configuration

- components/shared/Header/index.js
- components/shared/Header/styles.js
- containers/App.js
- package.json
- yarn.lock
Disables header transition between screens
> Change header display mode to float

- components/listings/Search/Button/index.js
- components/listings/Search/Button/styles.js
- components/listings/Search/index.js
- components/shared/Shell/index.js
- components/shared/Shell/styles.js
- containers/App.js
- containers/listings/Feed.js
- containers/listings/Search.js
- containers/views/Listings/index.js
- lib/api/index.js
- lib/services/listings.js
- package.json
- redux/modules/listings/feed/index.js
- redux/modules/listings/feed/saga.js
- yarn.lock
> Listings screen content and navigation

- components/listings/Gallery/index.js
- components/listings/Gallery/styles.js
- components/listings/Image.js
- components/listings/View/index.js
- components/listings/View/styles.js
- components/shared/Modal/index.js
- components/shared/Modal/styles.js
> Listing gallery

- components/listings/Card/index.js
- components/listings/Feed/TouchableCard/index.js
- components/listings/Feed/index.js
- components/listings/Gallery/index.js
- components/listings/Gallery/styles.js
- components/listings/Image.js
- components/listings/View/index.js
- components/listings/View/styles.js
- components/shared/Modal/index.js
- components/shared/Modal/styles.js
- containers/listings/View.js
- containers/views/Listing.js
- containers/views/index.js
- lib/services/listings.js
- redux/modules/listings/data/index.js
- redux/modules/listings/data/saga.js
- redux/modules/listings/data/selectors.js
- redux/modules/listings/feed/index.js
- redux/modules/listings/feed/selectors.js
- redux/modules/listings/saga.js
> Listing screen container

- assets/colors.js
- components/listings/View/Description/index.js
- components/listings/View/Description/styles.js
- components/listings/View/Properties/index.js
- components/listings/View/Properties/styles.js
- components/listings/View/index.js
- components/listings/View/styles.js
- components/shared/Price/index.js
- components/shared/Shell/index.js
- containers/views/Listing.js
> Listing properties

- .travis.yml
- android/app/build.gradle
- android/app/src/main/java/com/emcasa/MainApplication.java
- android/build.gradle
- android/settings.gradle
- assets/image.js
- components/listings/Gallery/index.js
- components/listings/Matterport/index.js
- components/listings/View/Thumbnail/index.js
- components/listings/View/Thumbnail/styles.js
- components/listings/View/index.js
- components/listings/View/styles.js
- package.json
- yarn.lock
> Matterport component

- components/listings/Card/index.js
- components/listings/Gallery/index.js
- components/shared/Modal/index.js
- components/shared/Orientation.js
> Fix orientation change responsiveness

- components/listings/View/Description/styles.js
- components/listings/View/Thumbnail/styles.js
- components/listings/View/index.js
- components/listings/View/styles.js
> Listing page styles

- components/listings/Matterport/index.js
- components/listings/Matterport/styles.js
- components/listings/View/Thumbnail/index.js
- components/listings/View/Thumbnail/styles.js
> Matterport thumbnail

- components/listings/Card/layouts/FullInfo/styles.js
> Tweak a few paddings and spacings in Listing Feed

- assets/colors.js
- components/interest/Form/Fields.js
- components/interest/Form/SelectType.js
- components/interest/Form/index.js
- components/interest/Form/interestTypes.js
- components/interest/Form/styles.js
- components/interest/Message/index.js
- components/interest/Message/styles.js
- components/listings/View/Thumbnail/index.js
- components/listings/View/index.js
- containers/interest/Form.js
- containers/listings/View.js
- containers/views/InterestForm.js
- containers/views/Listing.js
- containers/views/index.js
- lib/services/interest.js
- package.json
- redux/modules/interest/form/index.js
- redux/modules/interest/form/saga.js
- redux/modules/interest/form/selectors.js
- redux/modules/interest/index.js
- redux/modules/interest/saga.js
- redux/modules/interest/types/index.js
- redux/modules/interest/types/saga.js
- redux/modules/interest/types/selectors.js
- redux/modules/reducer.js
- redux/modules/saga.js
- yarn.lock
> Interest form

- components/interest/Calendly/index.js
- components/interest/Form/index.js
- components/interest/Form/styles.js
- containers/interest/Form.js
- containers/views/InterestForm/Calendly.js
- containers/views/InterestForm/Form.js
- containers/views/InterestForm/Message.js
- containers/views/InterestForm/index.js
> Calendly interest form

- components/shared/Shell/Header/index.js
- components/shared/Shell/Header/styles.js
- components/shared/Shell/index.js
- containers/listings/Listing/Price.js
- containers/listings/Listing/index.js
- containers/shared/Shell/Header.js
- containers/shared/Shell/index.js
- containers/views/Landing.js
- containers/views/Listing.js
> Change header layout

- components/listings/Listing/Navigation/index.js
- components/listings/Listing/Navigation/styles.js
- components/listings/Listing/Thumbnail/index.js
- components/listings/Listing/Thumbnail/styles.js
- components/listings/Listing/styles.js
- components/shared/Button/styles.js
> Listing icon buttons and footer

- components/interest/Form/Fields.js
- components/interest/Form/index.js
- components/interest/Form/styles.js
- components/shared/Button/styles.js
- components/shared/Separator/index.js
- components/shared/Separator/styles.js
- components/shared/TextInput/index.js
- components/shared/TextInput/styles.js
- containers/views/InterestForm/Form.js
> Interest form styles

- components/listings/Feed/Empty/index.js
- components/listings/Feed/Empty/styles.js
- components/listings/Feed/Results/index.js
- components/listings/Feed/Results/styles.js
- components/listings/Feed/index.js
- components/listings/Feed/layouts/Vertical.js
- containers/listings/Feed/index.js
- containers/views/Listings/Results.js
- redux/modules/listings/feed/saga.js
- redux/modules/listings/feed/selectors.js
> Listings feed indicators 

- components/listings/Feed/Results/index.js
- components/listings/Feed/Results/styles.js
> Change listings header phrase

- components/listings/Card/Body/components.js
- components/listings/Card/Body/styles.js
> Fix listings card text spacing

- components/listings/Map/Aggregator/Marker.js
- components/listings/Map/Aggregator/index.js
- components/listings/Map/Aggregator/styles.js
- components/listings/Map/index.js
- components/shared/InfiniteScroll/index.js
- containers/listings/Feed/Loader.js
- containers/listings/Feed/index.js
- containers/listings/Map.js
- containers/views/Listings/Map/Feed.js
- containers/views/Listings/Map/index.js
> Marker aggregator

- components/auth/ResetPassword/index.js
- components/auth/ResetPassword/styles.js
- containers/auth/Login.js
- containers/auth/ResetPassword.js
- containers/views/Auth/Login.js
- containers/views/Auth/ResetPassword.js
- containers/views/Auth/index.js
- lib/services/auth.js
- redux/modules/auth/index.js
- redux/modules/auth/saga.js
- redux/modules/fabric/saga.js
> Password reset screen

- components/shared/Form/Form/index.js
- components/shared/Form/Message/index.js
- components/shared/Form/Message/styles.js
- components/shared/Form/SubmitButton/index.js
- containers/auth/ResetPassword.js
- containers/auth/SignUp.js
- containers/views/Auth/ResetPassword.js
- containers/views/Auth/SignUp.js
- containers/views/Auth/Success.js
- containers/views/Auth/index.js
- redux/modules/auth/index.js
- redux/modules/auth/saga.js
- redux/modules/auth/selectors.js
> Auth success message screens

- .buildkite/deploy.sh
- .buildkite/hooks/post-checkout
- .buildkite/pipeline.yml
- components/listings/Listing/Thumbnail/index.js
- containers/views/Listings/Map/index.js
- containers/views/Listings/Results/index.js
- package.json
>  Fix map remounting when a marker is selected

- components/listings/Card/Listing/index.js
- components/listings/Card/Listing/styles.js
- components/listings/Feed/Listing/index.js
- containers/listings/Card/Listing.js
- containers/listings/Feed/Listing.js
- containers/listings/Listing/Loader.js
> Add like button to listings feed

- components/listings/LikeIcon.js
- components/listings/Listing/Description/index.js
- components/listings/Listing/Properties/index.js
- components/listings/Listing/Properties/styles.js
- components/listings/Listing/index.js
- components/listings/Listing/styles.js
- components/listings/Map/Marker/index.js
- components/listings/Map/Marker/styles.js
- components/listings/Map/index.js
> Update listing screen styles

- components/account/FormSection/index.js
- components/account/FormSection/styles.js
- components/account/PasswordForm/index.js
- components/account/PasswordForm/styles.js
- components/account/ProfileForm/index.js
- components/account/ProfileForm/styles.js
- components/shared/Form/SubmitHeader/index.js
- components/shared/Form/SubmitHeader/styles.js
- components/shared/TextInput/styles.js
- containers/account/PasswordForm.js
- containers/account/ProfileForm.js
- containers/views/Account/EditProfile.js
- lib/graphql/links/errorLink.js
> Fine tune profile forms

- components/listings/Image/index.js
> Improve thumbnail image resolution

- android/app/src/main/AndroidManifest.xml
- components/listings/Map/Aggregator/Marker.js
- components/listings/Map/Aggregator/styles.js
- components/listings/Map/index.js
- components/shared/Form/SubmitHeader/index.js
- components/shared/Form/SubmitHeader/styles.js
- containers/shared/Permission.js
- containers/views/Listings/Map/index.js
- ios/EmCasa.xcodeproj/project.pbxproj
- package.json
- yarn.lock
* [Center map on user's location when they are in RJ](https://www.pivotaltracker.com/story/show/157790026)
* [Fixes slow updates in the map screen on android](https://www.pivotaltracker.com/story/show/157885840)
----
> Center map on user's location

- components/listings/Gallery/index.js
- components/listings/Gallery/styles.js
- components/shared/Modal/styles.js
> Gallery button styles

- lib/graphql/links/stateLink/resolvers/favorites/mutations.js
- lib/graphql/links/stateLink/resolvers/favorites/sync.js
- redux/modules/fabric/saga.js
Log graphql errors to crashlytics in production and show a red screen in development.
> Graphql error reporting

- .circleci/config.yml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/emcasa/MainApplication.java
- android/app/src/main/res/xml/filepaths.xml
- android/settings.gradle
- ios/EmCasa.xcodeproj/project.pbxproj
- ios/EmCasa/Info.plist
- package.json
- patches/react-native-permissions+1.1.1.patch
- src/components/listings/Listing/Thumbnail/index.js
- src/lib/config.js
- src/screens/modules/listing/Listing/index.js
- yarn.lock
> Share button

- src/components/newListing/Address/AutoComplete/AutoComplete.js
- src/components/newListing/Address/index.js
- src/components/newListing/Properties/index.js
- src/components/shared/Form/TextInput.js
- src/screens/modules/listingForm/Properties/index.js
Fixes:
https://www.pivotaltracker.com/story/show/159157526
https://www.pivotaltracker.com/story/show/159157480
https://www.pivotaltracker.com/story/show/159157464
> Text input improvements

- __e2e__/screens/Listing/selectors.js
- __e2e__/screens/listing/screen.spec.js
- src/components/listings/Gallery/index.js
- src/components/listings/Listing/Thumbnail/index.js
>  Render gallery on listing screen header

- src/components/listings/Listing/Description/index.js
- src/components/listings/Listing/Description/styles.js
> Display listing id on listing screen

- __e2e__/screens/listing/interactions.js
- __e2e__/screens/listing/screen.spec.js
- package.json
- src/components/layout/BottomTabs/index.js
- src/components/layout/Modal.js
- src/components/listings/Gallery/index.js
- src/components/listings/Listing/Header.js
- src/components/listings/Listing/index.js
- src/components/listings/Matterport/index.js
- src/components/listings/SearchLocation/index.js
- src/screens/modules/listing/Listing/index.js
- yarn.lock
> Add 3d tour slide to listing page

- src/components/layout/Header.js
- src/components/listings/Card/index.js
- src/components/listings/Listing/Header.js
- src/components/listings/RecommendedFilters/index.js
- src/components/shared/GradientOverlay.js
> Add dark gradient overlay to listing cards
